language: node_js
node_js:
  - "8.4"
cache: yarn
script:
  - yarn --version
  - yarn sass
#  - yarn check # error "nyc#yargs#cliui" is wrong version: expected "4.1.0", got "2.1.0"
  - yarn lint
  - yarn test
  - yarn test:nsp
  - yarn test:routes
  - yarn test:a11y
group: edge
sudo: required
